### ISSUE TITLE
please include LICENSE files in published crates

### ISSUE THREAD

**Issue by decathorpe** [Holllo/opml#3]
Both the Apache-2.0 and MIT licenses require that re-distributed sources contain the original license texts. LICENSE files for Apache-2.0 and MIT licenses are present in the git repository / Cargo workspace root, but that won't make "cargo publish" include them when publishing sources to crates.io. Please include those files in future published versions.

The "easiest" solution for this is usually to create symlinks (i.e. `opml_api/LICENSE-foo → ../LICENSE-foo`), assuming you're running "cargo publish" on a unix-like system that supports symlinks (this doesn't work on Windows as far as I know - there it's necessary to copy files into the target directories, since traditional symlinks are not supported on Windows).

**Comment by Bauke** [comment]
As of [1.1.1](https://github.com/Holllo/opml/releases/tag/1.1.1) they're now in the crates. :smile:

**Comment by decathorpe** [comment]
Thanks!
